### ISSUE TITLE
Set prerender to false

### ISSUE THREAD

**Issue by anasmano** [munxar/goapi#2]
Hello,

I am new to web programming. 

I have a question, can I set the prerender to false for certain pages whose content is dynamic ?

i have tried to set prerender to false, but i got error.

Thank you in advance.

**Comment by munxar** [comment]
Hey @anasmano 

If you new to web programming, I'd suggest you stick with plain [SvelteKit](https://kit.svelte.dev) as fullstack framework.

The embedding in a go app is very specific and not really something you should care about if you start to learn the web.
With SvelteKit you can add an api route in seconds or use the load functions and actions for a very simple way of getting and sending data to the server. 

If you however need a app with dynamic routes, I'd go with [spa mode](https://kit.svelte.dev/docs/single-page-apps) and embedd this in the go binary.

Hope this Info helps you.
